name: Deploy Demo Site

on:
  push:
    branches: ["main", "master"]
    paths:
      - "demo_app/static/**"
      - ".github/workflows/deploy_demo_pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo_app/static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
